version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: lingua_db
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: lingua_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    container_name: lingua_frontend
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  pgdata: